### PR TITLE
You can now jump by pressing space bar

### PR DESCRIPTION
**Pull request by Melimet**

### CODE REVIEW

**Comment by tulma95** [comment]
Very good patch. Didn't think about this.

**Comment by JoakimJoensuu** [comment]
Awesome feature!

**Comment by Melimet** [comment]
Thanks i work veri hard for this feature :)))))

**Comment by Melimet** [comment]
ps. i got 140 from mensa web test :))))

**Comment by JoakimJoensuu** [comment]
You must have done very intense code cannoning!

**Comment by Melimet** [comment]
yes i tyckits code very angrerly :))))

**Pull request merged**
